[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1CZHA0hG1dhgcWKfWnWNUJ3rkYhFrazsjVit_aK2pTzw/"
type = "service_account"
project_id = "quan-ly-noi-tru"
private_key_id = "..."
private_key = """-----BEGIN PRIVATE KEY-----
(Bạn dán toàn bộ đoạn mã khóa từ file JSON gốc của Google vào đây. 
Hãy để nó xuống dòng tự nhiên y hệt như trong file gốc)
-----END PRIVATE KEY-----
"""
client_email = "..."
client_id = "..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "..."
